# CIDE::CLI is essentially a big dispatcher, no need to break it
# in smaller chunks.
Metrics/ClassLength:
  Max: 200

# CIDE::CLI methods can be read top to bottom. No need to factor out
# functionality unless it can be shared.
Metrics/MethodLength:
  Max: 60

# Don't align stuff vertically, bad for diffing
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# Allows for easy diffing
# Keep them sorted alphabetically unless a meaningful order exists
Style/TrailingComma:
  EnforcedStyleForMultiline: comma

# $? is not equivalent to $CHILD_STATUS
Style/SpecialGlobalVars:
  Enabled: false

# Prefering the short style
Style/PerlBackrefs:
  Enabled: false
