AllCops:
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'

# Rubocop is not smart enough
Metrics/AbcSize:
  Enabled: false

# CIDE::CLI is essentially a big dispatcher, no need to break it
# in smaller chunks.
Metrics/ClassLength:
  Enabled: false

# Offense count: 28
Metrics/CyclomaticComplexity:
  Enabled: false

# CIDE::CLI methods can be read top to bottom. No need to factor out
# functionality unless it can be shared.
Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 20

# Don't align stuff vertically, bad for diffing
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# Don't obsess over missing documentation for now
Style/Documentation:
  Enabled: false

# Don't agree with rubocop here
Style/MultilineOperationIndentation:
  Enabled: false

# Prefering the short style
Style/PerlBackrefs:
  Enabled: false

# $? is not equivalent to $CHILD_STATUS
Style/SpecialGlobalVars:
  Enabled: false

# Allows for easy diffing
# Keep them sorted alphabetically unless a meaningful order exists
Style/TrailingComma:
  EnforcedStyleForMultiline: comma

